### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by shogomuranushi** [shogomuranushi/kml#1]
### Node pools
- [x] Add detailed explanation and how to custom node-pools

### Jupyter
- [ ] How to custom image
- [ ] Using and mounting persistent volumes
- [ ] Using and mounting shared volumes
- [ ] Add detailed explanation and usage

### GPU Pod
- [ ] Add other GPU node pools
  - [ ] And nodeSelector to specific GPU type
- [ ] Using and mounting persistent volumes
- [ ] Using and mounting shared volumes
- [ ] Add detailed explanation and usage
- [ ] How to usage exec (ssh)

### README
- [ ] Update initialize description
- [ ] Update usage instructions
